const money = new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:2});
const pages=[...document.querySelectorAll('.page')];
const nav=[...document.querySelectorAll('[data-route]')];
function route(){const name=(location.hash||'#home').slice(1);const target=pages.find(p=>p.dataset.page===name)||pages[0];pages.forEach(p=>p.classList.toggle('active',p===target));nav.forEach(a=>a.classList.toggle('active',a.dataset.route===target.dataset.page));document.getElementById('mobileNav').hidden=true;document.getElementById('menuButton').setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:'instant'});}
addEventListener('hashchange',route);route();
const menu=document.getElementById('menuButton'),mobile=document.getElementById('mobileNav');menu.addEventListener('click',()=>{mobile.hidden=!mobile.hidden;menu.setAttribute('aria-expanded',String(!mobile.hidden))});
const annual=document.getElementById('annualPension'),lump=document.getElementById('lumpSum'),slider=document.getElementById('lumpSlider'),output=document.getElementById('lumpOutput');
const numeric=v=>Number(String(v).replace(/[^0-9.]/g,''));
const formatInput=v=>Number.isFinite(v)?new Intl.NumberFormat('en-GB',{maximumFractionDigits:0}).format(v):'';
slider.addEventListener('input',()=>{lump.value=formatInput(Number(slider.value));output.value=money.format(Number(slider.value))});
lump.addEventListener('input',()=>{const n=numeric(lump.value);if(Number.isFinite(n)){slider.value=Math.min(100000,n);output.value=money.format(n)}});
lump.addEventListener('blur',()=>{const n=numeric(lump.value);if(Number.isFinite(n))lump.value=formatInput(n)});annual.addEventListener('blur',()=>{const n=numeric(annual.value);if(Number.isFinite(n))annual.value=formatInput(n)});
document.getElementById('calculatorForm').addEventListener('submit',e=>{e.preventDefault();const a=numeric(annual.value),l=numeric(lump.value);const ae=document.getElementById('annualError'),le=document.getElementById('lumpError');ae.textContent='';le.textContent='';document.getElementById('results').hidden=true;if(!Number.isFinite(a)||a<=0){ae.textContent='Enter an annual pension greater than £0.';annual.focus();return}if(!Number.isFinite(l)||l<0){le.textContent='Enter a lump sum of £0 or more.';lump.focus();return}const exchanged=l/12;if(exchanged>a){le.textContent=`That lump sum would require more pension than the ${money.format(a)} annual pension entered.`;lump.focus();return}const remaining=a-exchanged;document.getElementById('resultAnnual').textContent=money.format(remaining);document.getElementById('resultMonthly').textContent=`${money.format(remaining/12)} per month`;document.getElementById('resultLump').textContent=money.format(l);document.getElementById('resultExchanged').textContent=money.format(exchanged);document.getElementById('startingPension').textContent=money.format(a);document.getElementById('resultBar').style.width=`${Math.max(0,remaining/a*100)}%`;document.getElementById('calculationText').textContent=`${money.format(l)} ÷ 12 = ${money.format(exchanged)} annual pension exchanged. ${money.format(a)} - ${money.format(exchanged)} = ${money.format(remaining)} annual pension remaining.`;const results=document.getElementById('results');results.hidden=false;results.scrollIntoView({behavior:'smooth',block:'start'})});
document.getElementById('printButton').addEventListener('click',()=>print());
const modal=document.getElementById('helpModal');document.querySelectorAll('[data-help]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('helpText').textContent=b.dataset.help;modal.hidden=false;modal.querySelector('.modal-close').focus()}));document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>modal.hidden=true));modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true});
const banner=document.getElementById('consentBanner'),status=document.getElementById('consentStatus');function showConsent(){banner.hidden=false}function setConsent(v){sessionStorage.setItem('pc-consent',v);banner.hidden=true;status.textContent=`You ${v} non-essential technologies for this browser session. No live advertising or analytics is connected.`}document.querySelectorAll('[data-consent]').forEach(b=>b.addEventListener('click',()=>setConsent(b.dataset.consent)));document.getElementById('reviewConsent').addEventListener('click',showConsent);const saved=sessionStorage.getItem('pc-consent');if(saved)setConsent(saved);else setTimeout(showConsent,600);document.getElementById('year').textContent=new Date().getFullYear();
