import {calculateCompensation,formatCompensationResult} from './compensation-engine.js';
import {calculateEPA,formatEPA} from './epa-engine.js';
import {calculateAddedPension,formatAddedPension} from './added-pension-engine.js';
const pages=[...document.querySelectorAll('.page')],nav=[...document.querySelectorAll('nav a')],mobile=document.getElementById('mobile'),menu=document.getElementById('menu');function route(){const n=(location.hash||'#home').slice(1),p=pages.find(x=>x.dataset.page===n)||pages[0];pages.forEach(x=>x.classList.toggle('active',x===p));nav.forEach(x=>x.classList.toggle('active',x.hash==='#'+p.dataset.page));mobile.hidden=true;scrollTo(0,0)}addEventListener('hashchange',route);route();menu.onclick=()=>mobile.hidden=!mobile.hidden;
const num=v=>Number(String(v).replace(/[^0-9.]/g,'')),gbp=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'});
document.getElementById('lumpForm').onsubmit=e=>{e.preventDefault();const a=num(annualPension.value),l=num(chosenLump.value);lumpError.textContent='';if(!(a>0)||!(l>=0)||l/12>a){lumpError.textContent='Enter valid figures. The chosen lump sum cannot exchange more annual pension than entered.';return}const ex=l/12,remain=a-ex;lumpAnnual.textContent=gbp.format(remain);lumpMonthly.textContent=gbp.format(remain/12);lumpAmount.textContent=gbp.format(l);lumpExchanged.textContent=gbp.format(ex);lumpResults.hidden=false;lumpResults.scrollIntoView({behavior:'smooth'})};
partTime.onchange=()=>partTimeFields.hidden=!partTime.checked;document.querySelectorAll('[name=compType]').forEach(r=>r.onchange=()=>veOptions.hidden=r.value!=='voluntary-exit');
document.getElementById('compForm').onsubmit=e=>{e.preventDefault();compError.textContent='';try{const type=document.querySelector('[name=compType]:checked').value;const result=calculateCompensation({type,dateOfBirth:dob.value,firstDayOfContinuousService:startDate.value,lastDayOfService:lastDate.value,normalPensionDate:pensionDate.value,reckonableServiceYears:num(service.value),basicSalary:num(salary.value),pensionableAllowances:num(allowances.value||0),partTime:partTime.checked,partTimeHours:num(ptHours.value),fullTimeHours:num(ftHours.value),fullTimeEquivalentServiceYears:num(fteService.value),lowerPaidUnderpin:underpin.checked,standardTariffMultiple:num(multiple.value),runStatutoryTest:true});renderComp(formatCompensationResult(result))}catch(err){compError.textContent=err.message}};
function renderComp(r){const b=r.breakdown,d=r.display,names={'voluntary-exit':'Voluntary Exit','voluntary-redundancy':'Voluntary Redundancy','compulsory-redundancy':'Compulsory Redundancy'};finalAward.textContent=d.finalAward;awardType.textContent=names[r.type]+(r.statutorySubstituted?' · statutory amount substituted':'');schemeAward.textContent=d.schemeAward;payUsed.textContent=gbp.format(b.calculationPay);monthlyPay.textContent=d.monthlyPay;serviceUsed.textContent=b.reckonableServiceYears.toFixed(4)+' years';standardTariff.textContent=d.standardTariff;applicableMax.textContent=d.applicableMaximum;monthsToPA.textContent=b.monthsToPensionAge+' months';statutoryAmount.textContent=d.statutoryAmount;compBreakdown.innerHTML=`<p><b>Pay used:</b> ${gbp.format(b.calculationPay)}</p><p><b>Standard tariff:</b> ${gbp.format(b.standardTariff)}</p><p><b>${b.maxMonths}-month scheme cap adjusted for pension age${r.inputs.partTime?' and part-time service':''}:</b> ${gbp.format(b.applicableMaximum)}</p><p><b>Scheme illustration:</b> ${gbp.format(r.schemeAward)}</p><p><b>Statutory comparison:</b> ${gbp.format(r.statutory.amount)}</p>`;compWarnings.innerHTML=r.warnings.map(x=>`<p>${x}</p>`).join('');compResults.hidden=false;compResults.scrollIntoView({behavior:'smooth'})}printComp.onclick=()=>print();

document.getElementById('epaForm').onsubmit=e=>{e.preventDefault();epaError.textContent='';try{const r=formatEPA(calculateEPA({dateOfBirth:epaDob.value,epaStartDate:epaStart.value,normalPensionDate:epaNpaDate.value,pensionableEarnings:num(epaSalary.value),option:Number(document.querySelector('[name=epaOption]:checked').value)}));epaRate.textContent=r.display.percentageOfEarnings;epaMonthly.textContent=r.display.monthlyCost;epaAnnual.textContent=r.display.annualCost;epaOptionResult.textContent='EPA-'+r.option;epaNpa.textContent=r.normalPensionAge.years+' years '+r.normalPensionAge.months+' months';epaBreakdown.innerHTML=`<p><b>2026 factor used:</b> ${r.contractRate}</p><p><b>Pensionable earnings:</b> ${gbp.format(num(epaSalary.value))}</p><p><b>Annual cost:</b> factor × earnings = ${r.display.annualCost}</p><p><b>Monthly cost:</b> annual cost ÷ 12 = ${r.display.monthlyCost}</p>`;epaWarnings.innerHTML=r.warnings.map(x=>`<p>${x}</p>`).join('');epaResults.hidden=false;epaResults.scrollIntoView({behavior:'smooth'})}catch(err){epaError.textContent=err.message}};

function syncAP(){const d=document.querySelector('[name=apDirection]:checked').value;apAmountLabel.childNodes[0].nodeValue=d==='payment-to-pension'?'One-off payment':'Target annual added pension'}document.querySelectorAll('[name=apDirection]').forEach(x=>x.onchange=syncAP);syncAP();apCover.onchange=()=>apSexLabel.hidden=apCover.value==='dependants';document.getElementById('apForm').onsubmit=e=>{e.preventDefault();apError.textContent='';try{const r=formatAddedPension(calculateAddedPension({direction:document.querySelector('[name=apDirection]:checked').value,dateOfBirth:apDob.value,contractStartDate:apStart.value,normalPensionDate:apNpaDate.value,amount:num(apAmount.value),cover:apCover.value,sex:apSex.value}));apResultTitle.textContent=r.direction==='payment-to-pension'?'Estimated annual added pension':'Estimated one-off payment required';apResult.textContent=r.display.result;apNpa.textContent=r.normalPensionAge.years+' years '+r.normalPensionAge.months+' months';apAge.textContent=r.ageAtContractStart;apNpaFactor.textContent=r.npaFactor;apRevFactor.textContent=r.revaluationFactor;apBreakdown.innerHTML=`<p><b>Input:</b> ${r.display.inputAmount}</p><p><b>Combined factor:</b> ${r.npaFactor} × ${r.revaluationFactor} = ${r.combinedFactor}</p><p><b>Calculation:</b> ${r.direction==='payment-to-pension'?'payment ÷ combined factor':'target pension × combined factor'}</p>`;apWarnings.innerHTML=r.warnings.map(x=>`<p>${x}</p>`).join('');apResults.hidden=false;apResults.scrollIntoView({behavior:'smooth'})}catch(err){apError.textContent=err.message}};
